//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fd73f650-2950-44a0-86ab-a35a983ee39b"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""ba2b842b-3f5c-4fb3-83eb-219eb3515445"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""cbe1b69e-ee87-44a4-b076-3a87d9e22674"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""a299f9af-95f1-47fd-bf72-fec244e341fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""a9c8dffd-02dc-46bc-aa77-d0e60902e6e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""3c4ac825-58e8-487f-8ba7-80b959d2a946"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Holster"",
                    ""type"": ""Button"",
                    ""id"": ""4989ad3b-04e9-4d5d-8aeb-d8f00ab4550b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lower Weapon"",
                    ""type"": ""Button"",
                    ""id"": ""48620936-869d-449d-a2b8-144b256bad4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6bf74daf-8a98-48de-b071-9a4f6efdc3f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grenade"",
                    ""type"": ""Button"",
                    ""id"": ""b48c7f02-acf4-4c91-9a97-f85d78b40a00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Melee"",
                    ""type"": ""Button"",
                    ""id"": ""ee72309b-00d2-4acf-aa85-8779c255d656"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""779a6091-f045-4535-8635-505915368372"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inspect"",
                    ""type"": ""Button"",
                    ""id"": ""f2d17bd7-8d54-496b-99fd-8cb954650514"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lock Cursor"",
                    ""type"": ""Button"",
                    ""id"": ""9beb2473-ee7d-4a54-857b-b42a64a66a65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory Next"",
                    ""type"": ""Button"",
                    ""id"": ""98c0547a-0a5e-484e-ba12-a7812face9b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory Next Wheel"",
                    ""type"": ""Value"",
                    ""id"": ""8dfbac0a-435e-4fa0-a00f-21b90315bd84"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Time Speed Up"",
                    ""type"": ""Button"",
                    ""id"": ""418359b7-9253-4bb8-a363-e1fb23da7133"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Time Speed Down"",
                    ""type"": ""Button"",
                    ""id"": ""e3ef7edf-7ab7-43b4-8fdc-67547435a45b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Time Speed Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""bfdda7d2-cee8-4cb7-91a0-f3d4411e7f97"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tutorial"",
                    ""type"": ""Button"",
                    ""id"": ""207fb2a2-8add-4ddb-bda7-c1887aeb313a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""885a3c54-aad8-4b06-8b4d-8a026bbb94f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Leaning"",
                    ""type"": ""Value"",
                    ""id"": ""26aac017-d754-4777-a1c8-2ae5121d9795"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Toggle Laser"",
                    ""type"": ""Button"",
                    ""id"": ""1500b140-0b9e-469c-91ca-e7f4462b5b66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""e1ba90be-8b16-4d83-b537-6b079e5a19ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AitomaticRifle"",
                    ""type"": ""Button"",
                    ""id"": ""a77d65ab-d8e0-4798-843f-09378fb47848"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pistol"",
                    ""type"": ""Button"",
                    ""id"": ""13727fc5-fa9b-4d15-aeee-3d85f6901d8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubmachineGun"",
                    ""type"": ""Button"",
                    ""id"": ""1408b17a-a0ed-44f3-987e-b85adda87cf0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shotgun"",
                    ""type"": ""Button"",
                    ""id"": ""7ee5d951-7d03-4351-a62a-4904456f5682"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SniperRifle"",
                    ""type"": ""Button"",
                    ""id"": ""e2f72f10-37be-49a3-8ec9-f77b97e912dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aeaa395a-3661-42a1-a33c-7a8c790be880"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8296c540-e14f-4d51-b70b-501abdfce15f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cffb61f-8b30-49c6-8800-6616f944844d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bde3ca2-883c-4584-bed3-9ec8a40d840e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3612ffab-101e-4e71-bfcd-6bf41f67f0e4"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6887bb4-0be9-409a-a15d-8003ce2787e5"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70861d89-1a53-4df4-99fe-73a6861806f3"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=2,y=2)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b85d03ba-6afe-4100-9072-d7bb950e8849"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.05,y=0.05)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc3a03f5-a9b8-4f03-a059-0934bff25be3"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Holster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f849bc7-a9ec-4751-9161-18b41a439450"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Holster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""150d2785-d381-47b7-aa2c-661f91c5e2f7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e60493f8-e05e-437f-99af-9b031cdd3c0f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f1f0667-d05b-44ff-b033-6af3c4c78b8b"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grenade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d06c74c-75fd-4f5f-95f2-6bd81b9f1d99"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grenade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ab3c0c1-413c-4596-93a8-b92c2eb0157b"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dd98274-256a-4623-973f-5995b0f261fa"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecd92882-b998-42f9-9dda-9d89419dd7c5"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54acc801-d1b1-4ca0-aa7e-13fbbca66d42"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73bd4a0a-ac64-41bf-8aca-a24b63708590"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inspect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0382ae6-6ecc-441e-a0a6-05fbc67523bb"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inspect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a482ba6-21ca-4c8f-9727-9fbb2368f00f"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Time Speed Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e79e440-5045-4bbc-a8a7-30167589d397"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Time Speed Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83f69484-fcc2-48ee-8c04-6c5d1e4f6e60"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Time Speed Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65c0a406-e8d6-434f-aeff-75269e0cbaaa"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Time Speed Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64767df0-dd96-438b-878e-fe24248339dd"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ced9121a-056b-40fc-a663-9d1e81066727"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bfee678-d7c2-4845-b78a-7b0479dbb478"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Time Speed Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6473f700-7e8d-42ea-a8d7-b52064620abb"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""cb6cccc0-3b41-4272-9fa9-a7193c1096be"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ce92f9ce-18c5-433a-847b-307059fae0f8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c3206dfb-ef32-4769-89dc-3a6a787f579a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9162ce15-88e6-4e92-b899-753cd4cdf604"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df75beb1-01b9-4794-a04e-7d65d8859e4f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""25b34351-c1db-469f-93c4-b2db927cb789"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory Next Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9837bdb8-e264-4c32-93bf-8013338f5c63"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lock Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac8aaf0e-baa6-466d-a2fd-5c3eb2bf85d7"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lock Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2c127bc-a838-4782-a49c-063fa51f1d76"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tutorial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a9054cd-1ecc-4095-a089-d0e32b67ab2c"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tutorial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e34aa957-68ff-4253-9abe-971e52e76acf"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93bda953-bb6f-4c70-aa9c-d0fd6d420ab7"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a228bb0-edfd-47a8-9460-9bfd27c254ae"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lower Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ba79389-e708-44b5-8bcd-b41de23140f5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lower Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Axis"",
                    ""id"": ""68aa6a8d-a25f-4d8e-9d6c-a30a3a8785d5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Leaning"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""59413d97-c602-4903-aad8-4431c1a75e61"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Leaning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""175d3f8c-31d0-4904-b1d8-63260c5ea0ad"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Leaning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""307728e7-3fce-4425-8ef6-4c59a83c83ae"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Laser"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca97e879-6f93-4998-a1a0-efd5ea2c25a9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Laser"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17563b9a-58b2-42c8-a076-6b072becd0e9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3bb831e-417c-421e-ac1a-d0b7ea51d41c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b181e77-f2ec-4cbf-af65-ef29867d185a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AitomaticRifle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51a18459-1c47-467d-99ce-0a2f67e5424f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pistol"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c590a3c4-d9bf-4f3e-9913-c7b8c6d84393"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubmachineGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""699ac9ef-244c-477f-a9b0-c62db0c37c2c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shotgun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5eef0e6-e6c6-46c3-b542-52465a111269"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SniperRifle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""be8390f8-51c1-4a70-9cb9-5418f57d4b57"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""910154ac-f94d-48c4-8d1f-3870768e5bd6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dab5b4be-beb8-4286-b196-666ae2486d0c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc96dee5-6317-43ab-a7e9-febd6d003c9a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
        m_Player_Aim = m_Player.FindAction("Aim", throwIfNotFound: true);
        m_Player_Reload = m_Player.FindAction("Reload", throwIfNotFound: true);
        m_Player_Holster = m_Player.FindAction("Holster", throwIfNotFound: true);
        m_Player_LowerWeapon = m_Player.FindAction("Lower Weapon", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Grenade = m_Player.FindAction("Grenade", throwIfNotFound: true);
        m_Player_Melee = m_Player.FindAction("Melee", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Inspect = m_Player.FindAction("Inspect", throwIfNotFound: true);
        m_Player_LockCursor = m_Player.FindAction("Lock Cursor", throwIfNotFound: true);
        m_Player_InventoryNext = m_Player.FindAction("Inventory Next", throwIfNotFound: true);
        m_Player_InventoryNextWheel = m_Player.FindAction("Inventory Next Wheel", throwIfNotFound: true);
        m_Player_TimeSpeedUp = m_Player.FindAction("Time Speed Up", throwIfNotFound: true);
        m_Player_TimeSpeedDown = m_Player.FindAction("Time Speed Down", throwIfNotFound: true);
        m_Player_TimeSpeedToggle = m_Player.FindAction("Time Speed Toggle", throwIfNotFound: true);
        m_Player_Tutorial = m_Player.FindAction("Tutorial", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Leaning = m_Player.FindAction("Leaning", throwIfNotFound: true);
        m_Player_ToggleLaser = m_Player.FindAction("Toggle Laser", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_AitomaticRifle = m_Player.FindAction("AitomaticRifle", throwIfNotFound: true);
        m_Player_Pistol = m_Player.FindAction("Pistol", throwIfNotFound: true);
        m_Player_SubmachineGun = m_Player.FindAction("SubmachineGun", throwIfNotFound: true);
        m_Player_Shotgun = m_Player.FindAction("Shotgun", throwIfNotFound: true);
        m_Player_SniperRifle = m_Player.FindAction("SniperRifle", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Restart = m_UI.FindAction("Restart", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Fire;
    private readonly InputAction m_Player_Aim;
    private readonly InputAction m_Player_Reload;
    private readonly InputAction m_Player_Holster;
    private readonly InputAction m_Player_LowerWeapon;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Grenade;
    private readonly InputAction m_Player_Melee;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Inspect;
    private readonly InputAction m_Player_LockCursor;
    private readonly InputAction m_Player_InventoryNext;
    private readonly InputAction m_Player_InventoryNextWheel;
    private readonly InputAction m_Player_TimeSpeedUp;
    private readonly InputAction m_Player_TimeSpeedDown;
    private readonly InputAction m_Player_TimeSpeedToggle;
    private readonly InputAction m_Player_Tutorial;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Leaning;
    private readonly InputAction m_Player_ToggleLaser;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_AitomaticRifle;
    private readonly InputAction m_Player_Pistol;
    private readonly InputAction m_Player_SubmachineGun;
    private readonly InputAction m_Player_Shotgun;
    private readonly InputAction m_Player_SniperRifle;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Fire => m_Wrapper.m_Player_Fire;
        public InputAction @Aim => m_Wrapper.m_Player_Aim;
        public InputAction @Reload => m_Wrapper.m_Player_Reload;
        public InputAction @Holster => m_Wrapper.m_Player_Holster;
        public InputAction @LowerWeapon => m_Wrapper.m_Player_LowerWeapon;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Grenade => m_Wrapper.m_Player_Grenade;
        public InputAction @Melee => m_Wrapper.m_Player_Melee;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Inspect => m_Wrapper.m_Player_Inspect;
        public InputAction @LockCursor => m_Wrapper.m_Player_LockCursor;
        public InputAction @InventoryNext => m_Wrapper.m_Player_InventoryNext;
        public InputAction @InventoryNextWheel => m_Wrapper.m_Player_InventoryNextWheel;
        public InputAction @TimeSpeedUp => m_Wrapper.m_Player_TimeSpeedUp;
        public InputAction @TimeSpeedDown => m_Wrapper.m_Player_TimeSpeedDown;
        public InputAction @TimeSpeedToggle => m_Wrapper.m_Player_TimeSpeedToggle;
        public InputAction @Tutorial => m_Wrapper.m_Player_Tutorial;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Leaning => m_Wrapper.m_Player_Leaning;
        public InputAction @ToggleLaser => m_Wrapper.m_Player_ToggleLaser;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @AitomaticRifle => m_Wrapper.m_Player_AitomaticRifle;
        public InputAction @Pistol => m_Wrapper.m_Player_Pistol;
        public InputAction @SubmachineGun => m_Wrapper.m_Player_SubmachineGun;
        public InputAction @Shotgun => m_Wrapper.m_Player_Shotgun;
        public InputAction @SniperRifle => m_Wrapper.m_Player_SniperRifle;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Fire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Aim.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Reload.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReload;
                @Holster.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHolster;
                @Holster.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHolster;
                @Holster.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHolster;
                @LowerWeapon.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLowerWeapon;
                @LowerWeapon.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLowerWeapon;
                @LowerWeapon.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLowerWeapon;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Grenade.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrenade;
                @Grenade.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrenade;
                @Grenade.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrenade;
                @Melee.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMelee;
                @Melee.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMelee;
                @Melee.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMelee;
                @Run.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Inspect.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInspect;
                @Inspect.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInspect;
                @Inspect.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInspect;
                @LockCursor.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLockCursor;
                @LockCursor.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLockCursor;
                @LockCursor.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLockCursor;
                @InventoryNext.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNext;
                @InventoryNext.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNext;
                @InventoryNext.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNext;
                @InventoryNextWheel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNextWheel;
                @InventoryNextWheel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNextWheel;
                @InventoryNextWheel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNextWheel;
                @TimeSpeedUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedUp;
                @TimeSpeedUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedUp;
                @TimeSpeedUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedUp;
                @TimeSpeedDown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedDown;
                @TimeSpeedDown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedDown;
                @TimeSpeedDown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedDown;
                @TimeSpeedToggle.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedToggle;
                @TimeSpeedToggle.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedToggle;
                @TimeSpeedToggle.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeSpeedToggle;
                @Tutorial.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTutorial;
                @Tutorial.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTutorial;
                @Tutorial.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTutorial;
                @Crouch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Leaning.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeaning;
                @Leaning.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeaning;
                @Leaning.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeaning;
                @ToggleLaser.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnToggleLaser;
                @ToggleLaser.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnToggleLaser;
                @ToggleLaser.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnToggleLaser;
                @Interact.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @AitomaticRifle.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAitomaticRifle;
                @AitomaticRifle.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAitomaticRifle;
                @AitomaticRifle.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAitomaticRifle;
                @Pistol.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPistol;
                @Pistol.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPistol;
                @Pistol.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPistol;
                @SubmachineGun.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmachineGun;
                @SubmachineGun.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmachineGun;
                @SubmachineGun.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmachineGun;
                @Shotgun.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShotgun;
                @Shotgun.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShotgun;
                @Shotgun.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShotgun;
                @SniperRifle.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSniperRifle;
                @SniperRifle.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSniperRifle;
                @SniperRifle.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSniperRifle;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @Holster.started += instance.OnHolster;
                @Holster.performed += instance.OnHolster;
                @Holster.canceled += instance.OnHolster;
                @LowerWeapon.started += instance.OnLowerWeapon;
                @LowerWeapon.performed += instance.OnLowerWeapon;
                @LowerWeapon.canceled += instance.OnLowerWeapon;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Grenade.started += instance.OnGrenade;
                @Grenade.performed += instance.OnGrenade;
                @Grenade.canceled += instance.OnGrenade;
                @Melee.started += instance.OnMelee;
                @Melee.performed += instance.OnMelee;
                @Melee.canceled += instance.OnMelee;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Inspect.started += instance.OnInspect;
                @Inspect.performed += instance.OnInspect;
                @Inspect.canceled += instance.OnInspect;
                @LockCursor.started += instance.OnLockCursor;
                @LockCursor.performed += instance.OnLockCursor;
                @LockCursor.canceled += instance.OnLockCursor;
                @InventoryNext.started += instance.OnInventoryNext;
                @InventoryNext.performed += instance.OnInventoryNext;
                @InventoryNext.canceled += instance.OnInventoryNext;
                @InventoryNextWheel.started += instance.OnInventoryNextWheel;
                @InventoryNextWheel.performed += instance.OnInventoryNextWheel;
                @InventoryNextWheel.canceled += instance.OnInventoryNextWheel;
                @TimeSpeedUp.started += instance.OnTimeSpeedUp;
                @TimeSpeedUp.performed += instance.OnTimeSpeedUp;
                @TimeSpeedUp.canceled += instance.OnTimeSpeedUp;
                @TimeSpeedDown.started += instance.OnTimeSpeedDown;
                @TimeSpeedDown.performed += instance.OnTimeSpeedDown;
                @TimeSpeedDown.canceled += instance.OnTimeSpeedDown;
                @TimeSpeedToggle.started += instance.OnTimeSpeedToggle;
                @TimeSpeedToggle.performed += instance.OnTimeSpeedToggle;
                @TimeSpeedToggle.canceled += instance.OnTimeSpeedToggle;
                @Tutorial.started += instance.OnTutorial;
                @Tutorial.performed += instance.OnTutorial;
                @Tutorial.canceled += instance.OnTutorial;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Leaning.started += instance.OnLeaning;
                @Leaning.performed += instance.OnLeaning;
                @Leaning.canceled += instance.OnLeaning;
                @ToggleLaser.started += instance.OnToggleLaser;
                @ToggleLaser.performed += instance.OnToggleLaser;
                @ToggleLaser.canceled += instance.OnToggleLaser;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @AitomaticRifle.started += instance.OnAitomaticRifle;
                @AitomaticRifle.performed += instance.OnAitomaticRifle;
                @AitomaticRifle.canceled += instance.OnAitomaticRifle;
                @Pistol.started += instance.OnPistol;
                @Pistol.performed += instance.OnPistol;
                @Pistol.canceled += instance.OnPistol;
                @SubmachineGun.started += instance.OnSubmachineGun;
                @SubmachineGun.performed += instance.OnSubmachineGun;
                @SubmachineGun.canceled += instance.OnSubmachineGun;
                @Shotgun.started += instance.OnShotgun;
                @Shotgun.performed += instance.OnShotgun;
                @Shotgun.canceled += instance.OnShotgun;
                @SniperRifle.started += instance.OnSniperRifle;
                @SniperRifle.performed += instance.OnSniperRifle;
                @SniperRifle.canceled += instance.OnSniperRifle;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Restart;
    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Restart => m_Wrapper.m_UI_Restart;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Restart.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRestart;
                @Restart.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRestart;
                @Restart.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRestart;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IPlayerActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnHolster(InputAction.CallbackContext context);
        void OnLowerWeapon(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnGrenade(InputAction.CallbackContext context);
        void OnMelee(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnInspect(InputAction.CallbackContext context);
        void OnLockCursor(InputAction.CallbackContext context);
        void OnInventoryNext(InputAction.CallbackContext context);
        void OnInventoryNextWheel(InputAction.CallbackContext context);
        void OnTimeSpeedUp(InputAction.CallbackContext context);
        void OnTimeSpeedDown(InputAction.CallbackContext context);
        void OnTimeSpeedToggle(InputAction.CallbackContext context);
        void OnTutorial(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnLeaning(InputAction.CallbackContext context);
        void OnToggleLaser(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAitomaticRifle(InputAction.CallbackContext context);
        void OnPistol(InputAction.CallbackContext context);
        void OnSubmachineGun(InputAction.CallbackContext context);
        void OnShotgun(InputAction.CallbackContext context);
        void OnSniperRifle(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnRestart(InputAction.CallbackContext context);
    }
}
